### ISSUE TITLE
List node output is limited to 10 stations

### ISSUE THREAD

**Issue by soeffi** [PfisterDaniel/node-red-contrib-tankerkoenig-api#1]
Hi!

For me the node unfortunately returns only 10 search results, while the API gives 40 stations for a specific search.

Diggind into the code, there is
https://github.com/PfisterDaniel/node-red-contrib-tankerkoenig-api/blob/cd02d9ddf65a9d3f018537a8d53fedb58d073d62/nodes/tankerkoenig.js#L250

I'm not that familiar with node-red, is there a particular reason to limit output? If required, would it be possible to make that limit configurable?

**Comment by PfisterDaniel** [comment]
Hi, no there is no particular reason to limit it. You can change it with remove .slice(0, 10)
i will chang this in a new version.

thank for report this error.

**Comment by PfisterDaniel** [comment]
Version 1.0.1 is published

**Comment by soeffi** [comment]
Great! Thanks for the quick reply!
