### ISSUE TITLE
Link not available in node infobox

### ISSUE THREAD

**Issue by soeffi** [PfisterDaniel/node-red-contrib-tankerkoenig-api#2]
Hi,

the following link is not visible in the infobox.
https://github.com/PfisterDaniel/node-red-contrib-tankerkoenig-api/blob/cd02d9ddf65a9d3f018537a8d53fedb58d073d62/nodes/tankerkoenig.html#L589

Probably because the `<a>` tag ends with an end marker "/>".

**Comment by PfisterDaniel** [comment]
Hi, 
the link its only availible on the Note-Settings window:
<img width="505" alt="Bildschirmfoto 2021-06-13 um 11 06 07" src="https://user-images.githubusercontent.com/9358627/121801422-7b5ea580-cc37-11eb-993a-5b7909d47d43.png">
it works...

Not in the Info Box.

**Comment by PfisterDaniel** [comment]
ahhh, i see the Error.
In a new Version is this solved :-D

thanks for report...

**Comment by PfisterDaniel** [comment]
Version 1.0.1 is published
